### ISSUE TITLE
GitHub user profile cache

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#2812]
Tracks how we cache GitHub user profile.

## Assumption
- User profiles are global and can be share across repos

## Goals
- Run `docfx build` many times should reuse the cache
- The cache could be shared across machines using `docfx restore` and `docfx publish`

## Draft spec:
- User profile cache has a config entry in `docfx.yml`, it points to either a file or an `URL`
- `docfx restore` download and place them in *%USERPROFILE%/.docfx/downloads/{url-sha2-hash}* if it is an URL.
- `docfx build` maintain a cache at *%USERPROFILE%/.docfx/cache/user-profile.json* from run to run.
  - Call GitHub API to fetch user profile, if missing or expired in the existing cache
  - **TBD** use soft expiration time to avoid spike API call to GitHub
- `docfx publish` POST updated `user-profiles.json` to the URL specified in config **only if** new contributors are found. *Etag* could be used for concurrency control.

### TODO
- [x] Query user profile using user name #3144 
- [x] Query user profile using commit info #3176
- [x] Use token to call GitHub API #3163 
- [x] Update user profile file
### Backlog
- [x] restore from URL
- [x] publish to URL #3673
- [x] log user profile update time for expiration use

@fenxu @superyyrrzz @OsmondJiang @herohua

**Comment by superyyrrzz** [comment]
>  `docfx build` creates `_site/user-profiles.json` **only if** there are new contributors

Is this needed? docfx can directly publish it from local cache, without a copy.

**Comment by yufeih** [comment]
@superyyrrzz you are right, I was under the impression that services wants it under output. It could be from the cache. Updated.

**Comment by herohua** [comment]
@yufeih @superyyrrzz will DocFX handle concurrent issue when multiple instances try writing to the same `user-profile.json` file?

@fenxu as FYI

**Comment by yufeih** [comment]
@herohua , yes, we could read the file on build start and write it once when build ends. Check *last modified time* before write and merge result in case some other process update the file during the build.

**Comment by herohua** [comment]
@yufeih 👍

**Comment by yufeih** [comment]
ETag hasn't been implemented yet, should we keep this issue open or we could live without etag handling?

**Comment by superyyrrzz** [comment]
@yufeih I will create another one tracking it.
