### ISSUE TITLE
Remaining work to build conceptual repos (target: azure-docs-pr)

### ISSUE THREAD

**Issue by herohua** [dotnet/docfx#2977]
Functionality (outside happy path)
- [x] Href: case sensitivity (#2966)
- [x] missing error code (#2863, @yufeih)
- [x] user profile cache (#2812, @superyyrrzz)

Functionality (targeting other repos, azure-docs-pr)
- [x] contributors_to_exclude (@928PJY)
- [x] experimental (@OsmondJiang)
- [x] document id: _op_documentIdPathDepotMapping

Functionality (enhancement, not in v2)
- [x] Yaml validation (#2838)
- [x] add line/column info in error message (#2874)

Performance
- [x] Performance testing and optimization (#2972)

Redesign
~~- [ ] Input/output schema (not legacy) (#2864)~~
- [x] Redirection (#2913)
- [x] TOC.md use markdig to parse (#2932)

Testing
- [x] TOC test failed randomly (#2950)
- [x] Improvement to impact testing (#2949)
- [x] Parallel testing (#2922)
~~- [ ] Ideal (not legacy) output impact testing~~

Onboarding/Usage
- [x] Document migration steps to enable v3 (#2999)

Issues:
- [x] Import tool issue: the resource file cannot be correctly imported when there is output mapping (#3090)
- [x] Routes have not be applied to the resource files (#3091)

@superyyrrzz @928PJY @live1206 @OsmondJiang @yufeih , feel free to add anything missing here. Thanks!
