### ISSUE TITLE
docfx build supports localization content

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3343]
- [x] 1. Support overwrite configuration for loc #3447
- [x] 2. Support file mappings between loc files and source files #3463 
- [x] 3. Support fallback during BUILD include resource/content #3463 
- [x] 4. Fallback items can be involved to build but NOT publish #3464 
- [x] 5. Support bilingual

**Comment by chri5topherus** [comment]
hi, 
is there any documentation on how to integrate localization (multilingual documentation)? 
Thanks for your help.
