### ISSUE TITLE
conceptual versioning in v3

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#3607]
[Dev spec](https://github.com/dotnet/docfx/blob/v3/docs/designs/conceptual-versioning.md)
# Phase 1 Tasks:
- [x] Support setting `monikerRange` and `monikerDefinitionUrl` in config. (@928PJY )
- [x] Support setting `monikerRange` in yaml header. (@live1206 )
- [x] Support `moniker zone` syntax in conceptual markdown file (@928PJY )
- [x] Internal Xref map with moniker info (@live1206 )
- [x] Input/output mapping (@928PJY )
- [x] File output content
    - [x] Legacy output(@live1206 )
    - [x] Conceptual file
    - [x] Redirection file (@928PJY )
    - [x] Toc file(@928PJY )
- [x] Build manifest file(@live1206 )
- [x] ~~Blank page support ?~~
- [x] API to get moniker definition file (@928PJY )
    - Convert the output of current API `/v2/monikertrees/allfamiliesproductsmonikers` to our expected model
    - Add two config items to global config in `Docs.Build`:
    ```
    monikerDefinition: https://op-build-sandbox2.azurewebsites.net/v2/monikertrees/allfamiliesproductsmonikers
    http:
        https://op-build-sandbox2.azurewebsites.net/v2/monikertrees/allfamiliesproductsmonikers:
            headers:
                X-OP-BuildUserToken: xxxx-xxxxx
    ```
- [ ] Impact repo test & migration tool support (@928PJY )
![pipeline](https://user-images.githubusercontent.com/17958546/48385749-af455780-e72a-11e8-9372-ab69794b1c59.jpg)

# Dependencies
- [ ] Support publishing with overlapping monikerRange to DHS.
- [x] Publish with the new manifest file(depend on the new manifest design & implementation).

# Remaining work after phase1:
- [ ] Reference validation:
    - [x] refenrece to internal uid with specific moniker 
    - [ ] refenrece to external uid with specific moniker 
    - [ ] refenrece to another file with specific moniker
- [ ] Output xref map with moniker info.
- [ ] Static site
    - [ ] implement fallback logic on build side.

**Comment by 928PJY** [comment]
Repository contains versioning:
- https://github.com/MicrosoftDocs/sql-docs-pr
- https://github.com/MicrosoftDocs/OfficeDocs-O365ITPro-pr
- https://github.com/aspnet/Docs
- https://github.com/MicrosoftDocs/CordovaDocs
- https://github.com/MicrosoftDocs/BingAds-docs
- https://github.com/MicrosoftDocs/vsdocs
- https://github.com/MicrosoftDocs/bot-docs-pr
- https://github.com/MicrosoftDocs/playfab-docs-rest-apis
- https://github.com/MicrosoftDocs/visualstudio-docs-pr
- https://github.com/MicrosoftDocs/MSGraph-Reference
- https://github.com/MicrosoftDocs/SystemCenterDocs-pr
- https://github.com/MicrosoftDocs/bingmaps-rest-api-docs
- https://github.com/MicrosoftDocs/ceapexpir-sandbox
- https://github.com/MicrosoftDocs/versioning-test
- https://github.com/MicrosoftDocs/office-developer-msproject-xml-docs
- https://github.com/MicrosoftDocs/cpp-docs-pr
- https://github.com/OPS-E2E-Prod/conceptual-version

**Comment by 928PJY** [comment]
open questions:
1. Do we need to support files with the same sitePath contains with-version and no-version output.
    - a.json: no version
    - a.json: netcore-1.0
    - a.json: netcore-2.0, netcore-3.0
2. When there are two same uid with different version, whose title should be taken as the displayName of the resolved href.
```
folder-1(1.0, 2.0):
   - a.md(uid: a, title A1)
   - b.md(@a)
folder-2(3.0,4.0):
   - a.md(uid: a, title A2)
   - b.md(@a)
```

**Comment by herohua** [comment]
this is now being tracked by https://dev.azure.com/ceapex/Engineering/_workitems/edit/78130
