### ISSUE TITLE
Update GitHub use cache aware of ETag

### ISSUE THREAD

**Issue by superyyrrzz** [dotnet/docfx#3718]
Follow #2812, Implement #3712

- [x] Restore url with ETag recorded, using ETag to avoid duplicate download #3726 
- [x] Update cache in cache folder, instead of in restore folder #3740
- [x] Upload cache with ETag #3756
- [x] ~~**Optional**: `docfx gc` clean up restored cache~~

**Comment by yufeih** [comment]
Let's not worry about gc cleanup as the cache is too small.
