### ISSUE TITLE
Support incremental build for FileMetadata change

### ISSUE THREAD

**Issue by superyyrrzz** [dotnet/docfx#3816]
Now if `FileMetadata` in `docfx.json` changed, DocFX will force building all files. DocFX implements this by comparing current `configHash` with last `configHash` to determine whether current build is full.

A smarter solution is to check which files this `FileMetadata` change impacts, and only rebuild these files.

The implementation includes:

- [x] 1. Split the current `configHash` into `configHash` (without `FileMetadata` info) and `FileMetadataHash`. #3843
- [x] 2. Store `FileMetadata` config into cache. #3843
- [x] 3. Compare current `FileMetadata` and last `FileMetadata` to find the impacted files. The output is a list of globs. This is a pre-step before loading ~~models~~ changes. @partychen #3886 
- [x] 4. ~~Before loading model~~ **Along with `LoadChanges`**, check whether a file's `FileMetadata` is changed by checking whether it's in `FileMetadatChangedGlobs`, to determine incremental build or not. We should enshure this check is before `ExpandDependency`. #3843

@herohua @fenxu
