### ISSUE TITLE
Use absolute URL for intermediate representation

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#4078]
We are currently using relative URL for intermediate representation, this complicates URL handling logic and makes html caching difficult for markdown inclusion and SDP. We could instead use absolute URL for intermediate representation and convert absolute URLs to relative URLs in the final HTML post processing stage. We are going to have an HTML post processing stage regardless so there is unlikely performance penalty.

> SCOPE: This issue does not track how we cache inclusion or SDP, it just defines the intermediate HTML representation that is cache friendly.

### Design

Intermediate HTML contains `data-linktype` and absolute URL (starting with `/`) for links that points to files:

Type | Markdown | HTML
---|---|---
External | `[](https://docs.com)` | `<a data-linktype="external" href="https://docs.com"></a>`
AbsolutePath | `[](/azure)` | `<a data-linktype="absolute-path" href="/azure"></a>`
RelativePath | `[](a.md)` | `<a data-linktype="relative-path" href="/basepath/a"></a>`
RelativePath with error | `[](a.md)` | `<a data-linktype="relative-path" href="a.md"></a>`
Bookmark | `[](#anchor)` | `<a data-linktype="self-bookmark" href="#anchor"></a>`

In HTML post process, all links are turned into relative URL if it satisfy both:
1. `data-linktype` is `relative-path`
2. `href` starts with `/`

> The above design also applies to images (`<img src="xxx">`)

### Work Items

- [ ] Move `data-linktype` generation from HTML post process to markup
- [ ] Generate absolute URLs in markup
- [ ] Convert absolute URL to relative URL in HTML post process
