### ISSUE TITLE
Code `TODO` clean up and improvement

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#4259]
- [x] cleanup docset model
  - [x] split data and behavioral objects
  - [x] define what configs should passed to dependency docsets and localization docsets (future)
- [x] cleanup document model
  - [x] split data and behavioral objects
- [ ] remove landing page link resolver hacking (future)
- [x] get line info of TOC href for bookmark validation&file-not-found (progressing)
- [x] get ride of `.GetAwaiter().GetResult()` if possible
- [x] reduce unnecessary Async/Await caused by RunInsideMutex()
- [ ] word count is not really correct (future)
- [x] clear model (interface) between docfx and template (progressing)
- [x] add missing line info (progressing)
- [x] Change `Range` from `Struct` to `Class` to avoid write `in` everywhere (progressing)
- [x] combine restore map and dependency lock model in build pipeline

**Comment by yufeih** [comment]
For loc:
- Loc docset is right now a doubly linked list (docset <--> localization docset <--> fallback docset), a singly linked list is easier to reason if we just have (docset --> fallback docset)
- If it is too complicated to support building loc from english, we can drop folder convention and only support build from loc.

**Comment by OsmondJiang** [comment]
For Config:

- [ ] Simplify `Global Config`. `Extended Config` and `Overwrite Config`
- [ ] Define `options`, `environment variables` and `config`
