### ISSUE TITLE
Build a virtual file system

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#6835]
[AB#342653](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/342653)

- [x] Create the docset package during initialization which provides the interface for accessing the files in the current docset. (#6836, #6853)
- [x] Apply package to config loader (#6836, #6840 )
- [x] Apply package to ContributionProvider (#6841)
- [x] Apply package to RedirectionProvider (#6842)
- [x] Apply package to ExternalXrefMapLoader (#6842)
- [x] Apply package to FileResolver (#6841)
- [x] Apply package to TemplateEngine (#6841)
- [x] ~~Apply package to Validation library (For now, only the ruleset need to access the file system, which is not in the scope of real-time validation)~~
- [x] Support MemoryPackage which hosts all the files in memory without touching file system. (#6857)
- [x] Support CompositePackage which maintaining multiple packages and handle the fallback. (#6857)
- [x] Apply MemoryPackage to our spec test. (#6857)
