### ISSUE TITLE
[Feature Request] Publish docfx packages in the name of .NET foundation

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#8930]
Today docfx NuGet packages are published in the name of Microsoft. With the transition to .NET foundation, future versions of docfx will be published in the name of .NET foundation.

This will introduce a breaking change to all packages starting with `Microsoft.*`, as those packages can only be published with a Microsoft signing cert. The candidate new package and namespace naming conventions are: `Microsoft.DocAsCode.*` -> `Docfx.*` or `Microsoft.DocAsCode.*` -> `DocAsCode.*`

---

- [x] Change copyright in code to .NET foundation and contributors #8867
- [x] Getting the .NET foundation code signing certificate (https://github.com/dotnet-foundation/projects/issues/293)
- [x] Change copyright of NuGet packages to .NET foundation and contributors
- [x] Reserve package prefix on NuGet.org:  DocFx.* prefix is now owned by the docfx account leaving DocFx.Plugins.* public
- [x] Update docfx NuGet package names and namespaces
- [x] Fix source link signing #8900 
- [x] Transition the `docfx` nuget account
- [x] Investigate publishing .NET Foundation signed packages to NuGet
- [x] Investigate docfx publish failure
- [x] Publish new packages using the .NET foundation signing cert on GitHub actions
- [x] Deprecate old NuGet packages
- [x] Remove the existing private publish pipeline and associated signing cert and secrets
- [x] Re-enable package validation for `Docfx.App`.

**Comment by yufeih** [comment]
It appears we could reserve `Docfx.*` and leave `Docfx.Plugins.*` as public, which make sense to me as a naming convention for 3rd party plugins.

**Comment by yufeih** [comment]
I don't have exact details on how NuGet name reserve works. It seems reserving the `Docfx.*` prefix did make `docfx` prefix reserved but does not reserve package names starting with `docfx` such as `docfxabc`.

**Comment by Lulalaby** [comment]
> Why does https://www.nuget.org/packages/docfx show "Prefix Reserved" even though the "docfx" name does not include the dot that is in the "DocFX.*" prefix?

If someone requests a namespace reservation for `namespace.*` the NuGet team reserves 'namespace.' as wildcard and additionally `namespace` as single package name.

**Comment by yufeih** [comment]
Newer versions of `Docfx.*` packages have be published to NuGet.org successfully. The `docfx` package is pushed to NuGet but failed package validation due to signing cert change. Need to work with NuGet team together to get it fixed.

**Comment by yufeih** [comment]
The `v2.70.0` release is out and fully on .NET foundation 🚀

**Comment by Lulalaby** [comment]
Congrats! Happy that this is finally done ❤️🚀
