### ISSUE TITLE
PDF on Chromium

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#9343]
The `wkhtmltopdf` based PDF solution is flawed in many areas:
* PDF template out of sync with the site template: #9331, #9204, #8148, #7027, #3446
* Quality issues with the tool: #2446, #1785, #9329

This is a new PDF solution based on Chromium, by printing PDF files out of HTML pages using the HTML template for ordinary build.

- [x] PDF builder using chrome
- [x] PDF link to bookmarks
- [x] Command integration
- [x] Print media style adjustment
- [x] Download PDF button
- [x] Print cover page
- [x] ~~Config cover page as source path~~
- [x] TOC page
- [x] TOC page numbers #7386 
- [x] Page numbers  #2003 
- [x] Optimize Playwright binary size?
- [x] wkhtmltopdf deprecation
- [x] PDF generation perf tune
- [x] Test on default template
- [x] Update docs

**Comment by paulushub** [comment]
**About wkhtmltopdf**: This repository has been archived by the owner on Jan 2, 2023. It is now read-only.

Is the Playwright currently packaged with the releases?

**Comment by yufeih** [comment]
Playwright isn't packaged today, it is only for testing. If packaged, it would increase the size of published zip releases of each platform from ~60MB to ~100MB, and increase the size of the docfx tool package to 300MB due to redistribution of NodeJS runtime for many platforms.

Dependency on NodeJS isn't a bad thing as we probably need it for #661 and to replace JINT. We can probably set NodeJS as a pre-requisite instead of redistributing it if size is a concern.

**Comment by paulushub** [comment]
> Dependency on NodeJS isn't a bad thing as we probably need it for https://github.com/dotnet/docfx/issues/661 and to replace JINT.

Actually waiting for this for my solution. The release [v2.72.1](https://github.com/dotnet/docfx/releases/tag/v2.72.1) does not include the usual binary. Is this intentional?

**Comment by yufeih** [comment]
> > Dependency on NodeJS isn't a bad thing as we probably need it for #661 and to replace JINT.
> 
> Actually waiting for this for my solution. The release [v2.72.1](https://github.com/dotnet/docfx/releases/tag/v2.72.1) does not include the usual binary. Is this intentional?

No, there are some problems with NuGet.org's signing key setup causing publish failures that I need to consult their support. Obviously, they work on a different time-zone so it could take a while.

**Comment by filzrev** [comment]
> If packaged, it would increase the size of published zip releases of each platform from ~60MB to ~100MB, and increase the size of the docfx tool package to 300MB due to redistribution of NodeJS runtime for many platforms.

I'm using `Docfx.App` NuGet package and it's undesirable to increasing package size.
(Though It might be possible to excluding playwright assets via `PackageReference`)

Is is hard to separate PDF generation functionality to separate `docfx-pdf.exe` process.
And  docfx.exe's `docfx pdf` command operations are delegated to that process like dotnet-tools.

**Comment by yufeih** [comment]
It only affect the size of the `docfx` package not the size of `Docfx.App`.

**Comment by filzrev** [comment]
> It only affect the size of the docfx package not the size of Docfx.App.
I've intended `output bin size` that referencing `Docfx.App` NuGet package. 
It increase bin size about ~60MB to ~100MB as noted above.

It's desirable to use pre-installed node runtime.
(It's planned at https://github.com/microsoft/playwright-dotnet/issues/1850)

Additionally latest docfx main branch build consume twice as much disk space as before. (about 5GB increased)
Because `.playwright` resources are separately included by following output combinations.

- Projects
  - docfx
  - docfx.App
  - docfx.Tests
  - docfx.Snapshot.Tests
- TargetFrameworks 
  - net6.0
  - net7.0
  - net8.0
- Configuration
  - Debug
  - Release

**Note:**  
It might not be a problem on [Dev Drive environment](https://learn.microsoft.com/en-us/windows/dev-drive).
Because `CopyOnWrite` feature exists.

**Comment by paulushub** [comment]
**Issue**: API Page
Namespace links points to localhost.

**Comment by yufeih** [comment]
> **Issue**: API Page Namespace links points to localhost.

Seems to be caused by 404s on the pages themselves.

**Comment by paulushub** [comment]
**Task**:  Optimize Playwright binary size?
Since DocFX is plugin based, will it be possible to only install the playwright when needed?

**Comment by yufeih** [comment]
The biggest size factor is the redistrbution of NodeJS for 4 platforms in Playwright dotnet: https://github.com/microsoft/playwright-dotnet/issues/1850

I tend to leaning on Playwright team fixing the issue using approaches such as using system-wide NodeJS or [dynamically install NodeJS](https://github.com/microsoft/playwright-dotnet/issues/1850#issuecomment-1163446513)

**Comment by paulushub** [comment]
We know this is going to be difficult. For MS (on GitHub and Azure), more time used is better business. 
For developers we need to cut this time also for better business. 
Hope tools like DocFX make the right choice to avoid fragmentation. 

Since this playwright is bringing in quiet a baggage, defining the PDF build interfaces with implementations 
through Playwright and others might be a good compromise in my view. 
I am looking at other options including [WeasyPrint](http://weasyprint.org/), but will also require NodeJs
for the conversion of mermaid-js graphics. WeasyPrint depends on GTK, no simple road but having a choice
is better.
